spring:
  application:
    name: quizty-core

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:8443/auth/realms/quizty/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: frontend
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: https://localhost:8443/api/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: https://localhost:8443/auth/realms/quizty
            user-name-attribute: preferred_username

server:
  port: 9080

javax:
  net:
    ssl:
      trust-store: keystore.jks
      trust-store-password: changeit
