spring:
  application:
    name: quizty-core
  datasource:
    url: jdbc:postgresql://localhost:5438/qb_core
    username: quizbuilder_user
    password: quizbuilder_password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration #, classpath:db/dev/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_HOST:https://localhost:8443}/auth/realms/quizty/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: frontend
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: https://localhost:8443/api/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_HOST:https://localhost:8443}/auth/realms/quizty
            user-name-attribute: preferred_username

server:
  port: 9080

javax:
  net:
    ssl:
      trust-store: classpath:keystore.jks
      trust-store-password: changeit
